name: PassMass
description: PassMass a storage less password manager.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  adaptive_dialog: ^0.6.4
  shared_preferences: ^0.5.7+3
  receive_sharing_intent: ^1.4.0+2
  flutter_clipboard_manager: ^0.0.2
  crypto: ^2.1.5
  flutter_launcher_icons: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/passmass_128.png"
